services:
    log_generator:
        build: ./generator/. # build image from Dockerfile in generator folder
        image: log-generator:latest
        deploy:
            replicas: 3 # run identical container instances
        environment: # interval to generate log message in milliseconds
        - GENERATOR_INTERVAL=10000

    error_scanner:
        build: . # build from Dockerfile in current folder
        image: error-scanner:latest
        environment: # set socket path
        - DOCKER_HOST=unix:///var/run/docker.sock
        volumes: # map paths from host machine to container path
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./backend/data/docker_exchange/records.db:/app/data/docker_exchange/records.db"
        ports: # expose port
            - "5000:5000"