services:
    log_generator:
        image: log-generator:latest
        deploy:
            replicas: 3 # run identical container instances
        environment:
        - GENERATOR_INTERVAL=10000

    error_scanner:
        image: error-scanner:latest
        environment: # set socket path
        - DOCKER_HOST=unix:///var/run/docker.sock
        volumes: # connect socket paths
        - /var/run/docker.sock:/var/run/docker.sock
        ports: # expose port 5000
            - "5000:5000"

